Food/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name="home"),

    path('user_profile/', views.user_profile, name="user_profile"),
    path('update_profile/', views.update_profile, name="update_profile"),
    
    path('menus/', views.res_menu, name="menu"),
    path('item-details/<int:id>', views.item_details, name="item_details"),
    path('restaurant/', views.res_list.as_view(), name="restaurant"),
    path('restaurant_menu/<int:id>', views.res_menu, name="restaurant_menu"),

    path('rate/<int:id>', views.rate_item, name="rate-item"),
    path('comment/<int:id>', views.add_comment, name="comment-item"),
    path('comment/delete/<int:id>', views.delete_comment, name="delete-comment-item"),
    path('comment/edit/<int:id>/', views.edit_comment, name="edit-comment-item"),

    path('review/<int:id>', views.review, name="review"),
    path('review/delete/<int:id>', views.delete_review, name="delete_review"),

    path('add_to_wishlist/<int:id>', views.add_to_wishlist, name="add_to_wishlist"),
    path('remove_from_wishlist/<int:id>', views.remove_from_wishlist, name="remove_from_wishlist"),
    path('clear_wishlist', views.clear_wishlist, name="clear_wishlist"),
    path('wishlist/', views.wishlist, name="wishlist"),

    path('orders/', views.order_history, name="order_list"),

    path('cart/', views.order_cart, name="order_cart"),
    path('add_to_cart/<int:id>/', views.add_to_order_cart, name="add_to_order_cart"),
    path('edit_orders/<int:id>/', views.edit_order_cart, name="edit_order_cart"),
    path('remove_from_cart/<int:id>/', views.remove_from_order_cart, name="remove_from_order_cart"),
    path('cart/delete', views.delete_order_cart, name="delete_cart"),
    
    path('cart/apply_voucher', views.apply_voucher, name="apply_voucher"),
    path('cart/remove_voucher', views.remove_voucher, name="remove_voucher"),

    path('checkout/', views.checkout, name="checkout"),
    path('add_user_address/', views.add_user_address, name="user_address"),
    path('confirm/', views.order_confirm, name="order_confirm"),

    path('payment/<int:id>', views.payment, name="payment"),

    path('search_price_range/', views.search_price_range, name="search_price_range"),

    path('contact_us/', views.contact_us, name="contact_us_userview"),
]

TreatMe/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Food.views import registration_page, staff_registration, login_page, logout, search, rate_item


urlpatterns = [
    path('registration/', registration_page, name="registration"),
    path('registration/staff/', staff_registration, name="staff_registration"),
    path('login/', login_page, name="login"),
    path('logout/', logout, name="logout"),

    path('search_results/', search, name="query"),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name="password_reset_complete"),

    path('user/', include('Food.urls')),
    path('staff/', include('stuffs.urls')),
    path('super-admin/', include('administrator.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Food/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from Food.models import Profile
from django import forms
from .models import UserProfile

class UserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = ['is_manager']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'placeholder': 'Last Name'}),
            'email': forms.TextInput(attrs={'placeholder': 'example@gmail.com'}),
        }
        fields = ['first_name', 'last_name', 'email']


class ProfileUpdateForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        widgets = {
            'Phone_number': forms.TextInput(attrs={'placeholder': '+880xxxxxxxxxx'})
        }
        fields = ['Profile_picture', 'Phone_number']

templates/insert_restaurant.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Treat Me&emsp;|&emsp;Add Restaurant</title>
    <link rel="icon" href="{% static 'img/logo.png' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,700">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Login-Form-Clean.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Login-Form-Dark.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Navigation-with-Button.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Pretty-Footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Registration-Form-with-Photo.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Steps_tab.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/untitled.css' %}">
</head>

<body>
    <div class="steps">
        <h2>Registration</h2>
        <p>Please complete the following steps.</p>

        <div class="tab">
            <a href="#s1">
                <button class="tablinks" onclick="openCity(event, 'step1')">Step 1: Enter Your Information</button>
            </a>

            <a href="#s2">
                <button class="tablinks" onclick="openCity(event, 'step2')">Step 2: Add Restaurant Information</button>
            </a>

            <a href="#s3">
                <button class="tablinks" onclick="openCity(event, 'step3')">Step 3: Confirm</button>
            </a>
        </div>

        <div id="step1" class="tabcontent"></div>
        <div id="step2" class="tabcontent"></div>
        <div id="step3" class="tabcontent"></div>
    </div>

    <script>
        function openCity(evt, cityName)
        {
            var i, tabcontent, tablinks;
            tabcontent = document.getElementsByClassName("tabcontent");
        
            for (i = 0; i < tabcontent.length; i++)
            {
                tabcontent[i].style.display = "none";
            }
        
            tablinks = document.getElementsByClassName("tablinks");
        
            for (i = 0; i < tablinks.length; i++)
            {
                tablinks[i].className = tablinks[i].className.replace(" active", "");
            }
        
            document.getElementById(cityName).style.display = "block";
            evt.currentTarget.className += " active";


        }
    </script>

    <div class="register-photo">
        <div class="form-container">
            
            <form method="POST" action="{% url 'staff_registration' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="alert alert-success">
                    <h1 id="s1">Step 1 : Enter Your Information</h1>
                </div>

                <div class="emdiv" style="height: 100px;"></div>

                <tr>
                    <td>
                        <input class="form-control" type="text" name="username" placeholder="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_username"><br>
                    </td>
                </tr>
                
                <tr>
                    <td>
                        <input class="form-control" type="email" name="email" placeholder="email" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_email"><br>
                    </td>
                </tr>

                <tr>
                    <th><label for="id_password1"></label></th>
                    <td>
                        <input class="form-control" type="password" name="password1" placeholder="password" autocomplete="new-password" required id="id_password1"><br>
                    </td>
                </tr>

                <tr>
                    <th><label for="id_password2"></label></th>
                    <td>
                        <input class="form-control" type="password" name="password2" placeholder="password (retype)" autocomplete="new-password" required id="id_password2">
                    </td>
                </tr>
                <br><br>

                <div class="emdiv" style="height: 350px;"></div>

                <div class="alert alert-success">
                    <h1 id="s2">Step 2 : Add Restaurant Details</h1>
                </div>

                {% for field in r_form %}
                <div class="form-group row" style="margin-left: 20px;">
                    <label for="id_{{ field.name }}" class="col-2 col-form-label"> {{ field.label }} </label>
                    <div class="col-10">
                        {{ field }}
                    </div>
                </div>
                {% endfor %}

                <button id="s3" class="btn btn-primary btn-block" type="submit">Confirm</button><br>
            </form>
        </div>
    </div>

    {% for message in messages %}
    <div class="popup" id="msg">
        <div class="header">
            <h2>Notification</h2>
            <!-- <label for="click" class="fas fa-times"></label> -->
        </div>
        <label for="click" class="fa fa-bell"></label>
        <p>{{message}}</p>
        <!-- <div class="line"></div>
        <label for="click" class="close-btn">Close</label> -->
    </div>
    {% endfor %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox-plus-jquery.min.js"></script>
    <script>
        setTimeout(function(){
            if ($('#msg').length > 0)
            {
                $('#msg').remove();
            }
        }, 3000)
    </script>
</body>

</html>

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Treat Me&ensp;|&ensp;Login</title>
    <link rel="icon" href="{% static 'img/logo.png' %}">

    <style>
        body .login-clean
        {
            background:url("{% static 'img/children-flying-dragon-kite-4k-yz-2560x1600.jpg' %}") no-repeat;
        }
    </style>

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,700">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Login-Form-Clean.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Login-Form-Dark.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Navigation-with-Button.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Pretty-Footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Registration-Form-with-Photo.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/untitled.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/popup.css' %}">
</head>

<body>
    <div class="login-clean">
        <form method="POST" method="{% url 'login' %}" autocomplete="off">
            {% csrf_token %}
            <h2 class="sr-only">Login Form</h2>
            <div class="illustration"><i class="icon ion-ios-navigate"></i></div>
            
            <div class="form-group">
                <input class="form-control" type="text" name="username" placeholder="Email or username">
            </div>

            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password" id="password">
                <span class="eye"><i class="fa fa-eye" id="eye" aria-hidden="true" onclick="toggle()"></i></span>
            </div>
            
            <div class="form-group">
                <button class="btn btn-primary btn-block" type="submit">Log In</button>
            </div>
            
            <a href="{% url 'password_reset' %}" target="_blank" class="forgot forgot-bar">Forgotten password?</a>
            <p class="forgot" style="font-size:16px;margin-top:20px;">Not Registered?</p>

            <a class="btn btn-primary btn-block" href="../registration" style="color: white; text-decoration: none;">Create new account</a>
        </form>
    </div>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-6 footer-navigation">
                    <h3><a href="#">TREAT Me</a></h3>
                    <p class="links"><a href="#">Resturants</a><strong> · </strong><a href="#">Services</a><strong> · </strong><a href="#">Order </a><strong> </strong></p>
                    <p class="company-name">TREAT Me @2020</p>
                </div>
                <div class="col-md-4 col-sm-6 footer-contacts">
                    <div><span class="fa fa-map-marker footer-contacts-icon"> </span>
                        <p><span class="new-line-span">Gollamari Khulna, Bangladesh</span></p>
                    </div>
                    <div><i class="fa fa-phone footer-contacts-icon"></i>
                        <p class="footer-center-info email text-left"> 123456789</p>
                    </div>
                    <div><i class="fa fa-envelope footer-contacts-icon"></i>
                        <p> <a href="#" target="_blank">support@company.com</a></p>
                    </div>
                    <div><i class="fa fa-envelope footer-contacts-icon"></i>
                        <p> <a href="#" target="_blank">AtoZ@gmail.com</a></p>
                    </div>
                    
                </div>
                <div class="clearfix visible-sm-block"></div>
                <div class="col-md-4 footer-about">
                    <h4>About the company</h4>
                    <p> Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet. </p>
                    <div class="social-links social-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-github"></i></a></div>
                </div>
            </div>
        </div>
    </footer>

    {% for message in messages %}
    <div class="popup" id="msg">
        <div class="header">
            <h2>Notification</h2>
            <!-- <label for="click" class="fas fa-times"></label> -->
        </div>
        <label for="click" class="fa fa-bell"></label>
        <p>{{message}}</p>
        <!-- <div class="line"></div>
        <label for="click" class="close-btn">Close</label> -->
    </div>
    {% endfor %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox-plus-jquery.min.js"></script>
    <script>
        setTimeout(function(){
            if ($('#msg').length > 0)
            {
                $('#msg').remove();
            }
        }, 3000)
    </script>

    <script>
        var state = false;

        function toggle()
        {
            if (state)
            {
                document.getElementById('password').setAttribute('type', 'password');
                document.getElementById('eye').style.color='#7A797E';
                state = false;
            }

            else
            {
                document.getElementById('password').setAttribute('type', 'text');
                document.getElementById('eye').style.color='#5887EF';
                state = true;
            }
        }
    </script>
</body>

</html>

templates/password_reset.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Treat Me&ensp;|&ensp;Reset Password</title>
    <link rel="icon" href="{% static 'img/logo.png' %}">

    <style>
        .forgot
        {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            border: 2px solid black;
            padding: 2%;
            background-image: linear-gradient(wheat, white);
            box-sizing: border-box;
            border-radius: 10px;
            box-shadow: 5px 10px #888888;
        }

        .forgot h3
        {
            color: blue;
            margin-bottom: 5vh;
            font-size: 40px;
            font-variant: small-caps;
        }

        .forgot p
        {
            font-size: 18px;
        }

        .forgot .btn
        {
            position: relative;
            left: 35%;
            width: 30%;
            margin-top: 5vh;
        }

        .forgot .log
        {
            text-align: center;
            margin-top: 3vh;
        }
    </style>

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,700">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Login-Form-Clean.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Login-Form-Dark.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Navigation-with-Button.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Pretty-Footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Registration-Form-with-Photo.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/untitled.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/popup.css' %}">
</head>

<body>
    <div class="forgot">
        <h3>Password reset</h3>
        <p>Forgotten your password?<br><br>Enter your email address below, and we’ll email instructions for setting a new one.</p>
        
        <form method="POST" autocomplete="off">
            {% csrf_token %}
            {{ form }}<br>
            <input type="submit" value="Send verification Email" class="btn btn-success" name="Send email">

            <div class="log">
                or, <a href="{% url 'login' %}">Login</a> to your account.
            </div>
        </form>
    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox-plus-jquery.min.js"></script>
</body>

</html>

templates/password_reset_complete.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Treat Me&ensp;|&ensp;Reset Password</title>
    <link rel="icon" href="{% static 'img/logo.png' %}">

    <style>
        body .login-clean
        {
            background:url("{% static 'img/children-flying-dragon-kite-4k-yz-2560x1600.jpg' %}") no-repeat;
        }
    </style>

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,700">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Login-Form-Clean.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Login-Form-Dark.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Navigation-with-Button.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Pretty-Footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Registration-Form-with-Photo.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/untitled.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/popup.css' %}">
</head>

<body>
    <div class="alert alert-success">
        <h1><i class="fa fa-exclamation-circle"></i> Password has been reset successfully!</h1>
    </div>

    <h5 style="margin-left: 2%;">Password has been reset. You may <a href="{% url 'login' %}">Login</a> now using the password!</h5>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox-plus-jquery.min.js"></script>
</body>

</html>

templates/registration.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Treat Me&ensp;|&ensp;Registration</title>
    <link rel="icon" href="{% static 'img/logo.png' %}">

    <style>
        body .register-photo .form-container .image-holder
        {
            background:url("{% static 'img/meeting.jpg' %}") no-repeat;
        }
    </style>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,700">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Login-Form-Clean.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Login-Form-Dark.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Navigation-with-Button.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Pretty-Footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Registration-Form-with-Photo.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/untitled.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/popup.css' %}">
</head>

<body>
    <div class="register-photo">
        <div class="form-container">
            <div class="image-holder"></div>
            <form method="POST" action="{% url 'registration' %}">
                {% csrf_token %}
                <h2 class="text-center"><strong>Create</strong> an account.</h2>
                <tr>
                    <td>
                        <input class="form-control" type="text" name="username" placeholder="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_username"><br>
                    </td>
                </tr>
                
                <tr>
                    <td>
                        <input class="form-control" type="email" name="email" placeholder="email" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_email"><br>
                    </td>
                </tr>

                <tr>
                    <th><label for="id_password1"></label></th>
                    <td>
                        <input class="form-control" type="password" name="password1" placeholder="password" autocomplete="new-password" required id="id_password1"><br>
                    </td>
                </tr>

                <tr>
                    <th><label for="id_password2"></label></th>
                    <td>
                        <input class="form-control" type="password" name="password2" placeholder="password (retype)" autocomplete="new-password" required id="id_password2">
                    </td>
                </tr>
                <br>
                <tr>
                    <td>
                        <!-- <input class="" type="checkbox" name="is_manager"> Are you a restaurant stuff? -->
                    </td>
                </tr>
                <button class="btn btn-primary btn-block" type="submit">Sign Up</button><br>
            
                <p style="text-align: center;">You already have an account?</p>
                <div class="already"><a href="../login">Login here.</a></div>
                
                <div class="join" style="text-align: center;">
                    <br>Do your want your own restaurant on our apps?
                    <a href="{% url 'staff_registration' %}">Join Now</a>
                </div>
            </form>
        </div>
    </div>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-6 footer-navigation">
                    <h3><a href="#">TREAT Me</a></h3>
                    <p class="links"><a href="#">Resturants</a><strong> · </strong><a href="#">Services</a><strong> · </strong><a href="#">Order </a><strong> </strong></p>
                    <p class="company-name">TREAT Me @2020</p>
                </div>
                <div class="col-md-4 col-sm-6 footer-contacts">
                    <div><span class="fa fa-map-marker footer-contacts-icon"> </span>
                        <p><span class="new-line-span">Gollamari Khulna, Bangladesh</span></p>
                    </div>
                    <div><i class="fa fa-phone footer-contacts-icon"></i>
                        <p class="footer-center-info email text-left"> 123456789</p>
                    </div>
                    <div><i class="fa fa-envelope footer-contacts-icon"></i>
                        <p> <a href="#" target="_blank">support@company.com</a></p>
                    </div>
                    <div><i class="fa fa-envelope footer-contacts-icon"></i>
                        <p> <a href="#" target="_blank">AtoZ@gmail.com</a></p>
                    </div>
                    
                </div>
                <div class="clearfix visible-sm-block"></div>
                <div class="col-md-4 footer-about">
                    <h4>About the company</h4>
                    <p> Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet. </p>
                    <div class="social-links social-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-github"></i></a></div>
                </div>
            </div>
        </div>
    </footer>

    {% for message in messages %}
    <div class="popup" id="msg">
        <div class="header">
            <h2>Notification</h2>
            <!-- <label for="click" class="fas fa-times"></label> -->
        </div>
        <label for="click" class="fa fa-bell"></label>
        <p>{{message}}</p>
        <!-- <div class="line"></div>
        <label for="click" class="close-btn">Close</label> -->
    </div>
    {% endfor %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox-plus-jquery.min.js"></script>
    <script>
        setTimeout(function(){
            if ($('#msg').length > 0)
            {
                $('#msg').remove();
            }
        }, 3000)
    </script>
</body>

</html>