Food/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name="home"),

    path('user_profile/', views.user_profile, name="user_profile"),
    path('update_profile/', views.update_profile, name="update_profile"),
    
    path('menus/', views.res_menu, name="menu"),
    path('item-details/<int:id>', views.item_details, name="item_details"),
    path('restaurant/', views.res_list.as_view(), name="restaurant"),
    path('restaurant_menu/<int:id>', views.res_menu, name="restaurant_menu"),

    path('rate/<int:id>', views.rate_item, name="rate-item"),
    path('comment/<int:id>', views.add_comment, name="comment-item"),
    path('comment/delete/<int:id>', views.delete_comment, name="delete-comment-item"),
    path('comment/edit/<int:id>/', views.edit_comment, name="edit-comment-item"),

    path('review/<int:id>', views.review, name="review"),
    path('review/delete/<int:id>', views.delete_review, name="delete_review"),

    path('add_to_wishlist/<int:id>', views.add_to_wishlist, name="add_to_wishlist"),
    path('remove_from_wishlist/<int:id>', views.remove_from_wishlist, name="remove_from_wishlist"),
    path('clear_wishlist', views.clear_wishlist, name="clear_wishlist"),
    path('wishlist/', views.wishlist, name="wishlist"),

    path('orders/', views.order_history, name="order_list"),

    path('cart/', views.order_cart, name="order_cart"),
    path('add_to_cart/<int:id>/', views.add_to_order_cart, name="add_to_order_cart"),
    path('edit_orders/<int:id>/', views.edit_order_cart, name="edit_order_cart"),
    path('remove_from_cart/<int:id>/', views.remove_from_order_cart, name="remove_from_order_cart"),
    path('cart/delete', views.delete_order_cart, name="delete_cart"),
    
    path('cart/apply_voucher', views.apply_voucher, name="apply_voucher"),
    path('cart/remove_voucher', views.remove_voucher, name="remove_voucher"),

    path('checkout/', views.checkout, name="checkout"),
    path('add_user_address/', views.add_user_address, name="user_address"),
    path('confirm/', views.order_confirm, name="order_confirm"),

    path('payment/<int:id>', views.payment, name="payment"),

    path('search_price_range/', views.search_price_range, name="search_price_range"),

    path('contact_us/', views.contact_us, name="contact_us_userview"),
]

TreatMe/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Food.views import registration_page, staff_registration, login_page, logout, search, rate_item


urlpatterns = [
    path('registration/', registration_page, name="registration"),
    path('registration/staff/', staff_registration, name="staff_registration"),
    path('login/', login_page, name="login"),
    path('logout/', logout, name="logout"),

    path('search_results/', search, name="query"),

    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='password_reset.html'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name="password_reset_done"),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'), name="password_reset_confirm"),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name="password_reset_complete"),

    path('user/', include('Food.urls')),
    path('staff/', include('stuffs.urls')),
    path('super-admin/', include('administrator.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Food/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from stuffs.models import foodItem, restaurantList, Rating
from django.conf import settings
from accounts.models import UserAddress, UserDefaultAddress
from PIL import Image

User = get_user_model()

# Create your models here.
class Manager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Restaurant = models.OneToOneField(restaurantList, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.Restaurant.Restaurant_name} : {self.user.username}'


class Profile(models.Model):
   user = models.OneToOneField(User, on_delete=models.CASCADE)
   is_manager = models.BooleanField(verbose_name="is_manager", default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    Profile_picture = models.ImageField(default='default.jpg', upload_to='profile_pics')
    Phone_number = models.CharField(max_length=15, blank=True)

    def __str__(self):
        return f'{self.user.username} Profile'


    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.Profile_picture.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.Profile_picture.path)


class Wishlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    wished_item = models.ForeignKey(foodItem, on_delete=models.CASCADE)
    added_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} : {self.wished_item.Item_name}'


class Cart(models.Model):
    restaurant = models.ForeignKey(restaurantList, on_delete=models.CASCADE, null=True, blank=True)
    sub_total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)
    tax_total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    final_total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f'Cart : {self.id}'


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, null=True, blank=True, on_delete=models.CASCADE)
    product = models.ForeignKey(foodItem, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=0)
    comment = models.CharField(max_length=120, null=True, blank=True)
    line_total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        try:
            return f'Cart Id : {self.cart.id}'
        except:
            return self.product.Item_name


class Order(models.Model):
    STATUS_CHOICES = (
        ("Started", "Started"),
        ("Abandoned", "Abandoned"),
        ("Finished", "Finished")
    )

    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    order_id = models.CharField(max_length=120, default='ABCDEF', unique=True)
    transaction_id = models.CharField(max_length=120, default='ABCDEFGHIJKL')
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    restaurant = models.ForeignKey(restaurantList, on_delete=models.CASCADE, blank=True, null=True)
    status = models.CharField(max_length=120, choices=STATUS_CHOICES)
    address = models.OneToOneField(UserAddress, on_delete=models.CASCADE, blank=True, null=True)
    sub_total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    tax_total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    final_total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    charged = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    viewed = models.BooleanField(default=False)

templates/restaurantStuffs/addItem.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{rest.Restaurant_name}}&ensp;|&ensp;Add Item</title>
    <link rel="icon" href="{% static 'img/logo.png' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/ionicons.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/batch.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/integer_input_fix.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Pretty-Footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/myitems.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Navigation-with-Button.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/side-nav.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,700">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header" style="margin-left: -150px;">
                <a class="navbar-brand" href="{% url 'res_profile' %}">
                    <img src="{{rest.Logo.url}}" id="logo">
                    <strong style="font-size: 25px; color:teal">{{rest.Restaurant_name}}</strong>
                </a>
                
                <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav navbar-left" style="margin-left: 280px;">                    
                    <li class="last">
                        {% if user.is_authenticated %}
                            <span style="line-height: 60px; color:springgreen;font-weight:bold">Logged In as &nbsp;</span>
                            <span class="btn btn-info navbar-btn navbar-right" data-toggle="dropdown" aria-expanded="false" href="#">
                                {{user.username}}
                            </span>
                        {% else %}
                            <a href="{% url 'login' %}" class="btn btn-info navbar-btn navbar-right">
                                <i class="fa fa-unlock-alt"></i> Login
                            </a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <input type="checkbox" id="check">
    <label for="check">
        <i class="fa fa-bars" id="btn"></i>
        <i class="fa fa-times" id="cancel"></i>
    </label>

    <div class="sidebar">
        <header>
            <img src="{% static 'img/logo.png' %}"> Treat Me
        </header>

        <ul>
            <li><a href="{% url 'Homepage' %}"><i class="fa fa-qrcode"></i> Dashboard</a></li>
            <li><a href="{% url 'user_staff_profile' %}"><i class="fa fa-user"></i> User Profile</a></li>
            <li><a href="{% url 'res_profile' %}"><i>&#127860;</i> Restaurant overview</a></li>
            
            <li>
                <a href="{% url 'cus_orders' %}">
                    <i class="fa fa-cart-arrow-down"></i> Orders
                    <span class="badge badge-info" style="padding: 7px;"> {{order_count}}</span>
                </a>
            </li>
            
            <li>
                <a href="{% url 'myitems' %}">
                    <i class="fa fa-clipboard"></i> My Items
                    <span class="badge badge-info" style="padding: 7px;"> {{item_count}}</span>
                </a>
            </li>

            <li><a href="{% url 'contact_us_staffview' %}"><i class="fa fa-envelope"></i> Contact Us</a></li>
            <li><a href="{% url 'logout' %}"><i class="fa fa-lock"></i> Logout</a></li>
        </ul>
    </div>

    <div class="section">
        <div class="containerpart">
            <h2>Add Item</h2>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form %}
                    {% if field.name == 'onTrend' %}
                        {{ field }}
                        <label for="id_{{ field.name }}" class="col-2 col-form-label"> Is the food trending? </label><br>
        
                    {% else %}
                        <div class="form-group row">
                            <label for="id_{{ field.name }}" class="col-2 col-form-label"> {{ field.label }} </label>
                            <div class="col-10">
                                {{ field }}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
        
                <input type="submit" class="btn btn-primary" name="button" value="Add Item">
                <a href="{% url 'myitems' %}" class="btn btn-danger btn-sm" role="button">Cancel</a>
            </form>
        </div>

        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-6 footer-navigation">
                        <h3><a href="#">TREAT Me</a></h3>
                        <p class="links"><a href="#">Resturants</a><strong> · </strong><a href="#">Services</a><strong> · </strong><a href="#">Order </a><strong> </strong></p>
                        <p class="company-name">TREAT Me @2020</p>
                    </div>
                    <div class="col-md-4 col-sm-6 footer-contacts">
                        <div><span class="fa fa-map-marker footer-contacts-icon"> </span>
                            <p><span class="new-line-span">Gollamari Khulna, Bangladesh</span></p>
                        </div>
                        <div><i class="fa fa-phone footer-contacts-icon"></i>
                            <p class="footer-center-info email text-left"> 123456789</p>
                        </div>
                        <div><i class="fa fa-envelope footer-contacts-icon"></i>
                            <p> <a href="#" target="_blank">support@company.com</a></p>
                        </div>
                        <div><i class="fa fa-envelope footer-contacts-icon"></i>
                            <p> <a href="#" target="_blank">AtoZ@gmail.com</a></p>
                        </div>
                        
                    </div>
                    <div class="clearfix visible-sm-block"></div>
                    <div class="col-md-4 footer-about">
                        <h4>About the company</h4>
                        <p> Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet. </p>
                        <div class="social-links social-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-github"></i></a></div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox-plus-jquery.min.js"></script>
</body>
</html>

templates/restaurantStuffs/update_profile.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ user.username }}&emsp;|&emsp;Edit Profile</title>
    <link rel="icon" href="{% static 'img/logo.png' %}">
    
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway:400,700">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/css/lightbox.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/batch.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Login-Form-Clean.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Login-Form-Dark.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Navigation-with-Button.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/popup.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Pretty-Footer.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/Registration-Form-with-Photo.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/side-nav.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/untitled.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/user_profile.css' %}">
    
    <style>
        .update-content
        {
            margin: 5%;
        }

        .cont
        {
            margin: 2% 0;
        }

        .cont input
        {
            margin-top: 0.45%;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header" style="margin-left: -150px;">
                <a class="navbar-brand" href="{% url 'res_profile' %}">
                    <img src="{{rest.Logo.url}}" id="logo">
                    <strong style="font-size: 25px; color:teal">{{rest.Restaurant_name}}</strong>
                </a>
                
                <button class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navcol-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav navbar-left" style="margin-left: 280px;">                    
                    <li class="last">
                        {% if user.is_authenticated %}
                            <span style="line-height: 60px; color:springgreen;font-weight:bold">Logged In as &nbsp;</span>
                            <span class="btn btn-info navbar-btn navbar-right" data-toggle="dropdown" aria-expanded="false" href="#">
                                {{user.username}}
                            </span>
                        {% else %}
                            <a href="{% url 'login' %}" class="btn btn-info navbar-btn navbar-right">
                                <i class="fa fa-unlock-alt"></i> Login
                            </a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <input type="checkbox" id="check">
    <label for="check">
        <i class="fa fa-bars" id="btn"></i>
        <i class="fa fa-times" id="cancel"></i>
    </label>

    <div class="sidebar">
        <header>
            <img src="{% static 'img/logo.png' %}"> Treat Me
        </header>

        <ul>
            <li><a href="{% url 'Homepage' %}"><i class="fa fa-qrcode"></i> Dashboard</a></li>
            <li><a href="{% url 'user_staff_profile' %}"><i class="fa fa-user"></i> User Profile</a></li>
            <li><a href="{% url 'res_profile' %}"><i>&#127860;</i> Restaurant overview</a></li>
            
            <li>
                <a href="{% url 'cus_orders' %}">
                    <i class="fa fa-cart-arrow-down"></i> Orders
                    <span class="badge badge-info" style="padding: 7px;"> {{order_count}}</span>
                </a>
            </li>
            
            <li>
                <a href="{% url 'myitems' %}">
                    <i class="fa fa-clipboard"></i> My Items
                    <span class="badge badge-info" style="padding: 7px;"> {{item_count}}</span>
                </a>
            </li>

            <li><a href="{% url 'contact_us_staffview' %}"><i class="fa fa-envelope"></i> Contact Us</a></li>
            <li><a href="{% url 'logout' %}"><i class="fa fa-lock"></i> Logout</a></li>
        </ul>
    </div>
    
    <div class="section" style="margin-top: 150px;">
        <div class="update-content" style="margin-left:120px">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Update Profile</legend>
                    <p>* fields are required</p>

                    <div class="cont">
                        Upload a profile picture <br>
                        <input type="file" name="Profile_picture" accept="image/*" id="id_Profile_picture">
                    </div>
                    
                    <div class="cont">
                        First Name <br>
                        {{ u_form.first_name }}
                    </div>

                    <div class="cont">
                        Last Name <br>
                        {{ u_form.last_name }}
                    </div>

                    <div class="cont">
                        Phone Number <br>
                        {{ p_form.Phone_number }}
                    </div>

                    <div class="cont">
                        Email *<br>
                        {{ u_form.email }}
                    </div>
                    
                    <div class="form-group">
                        <button class="btn btn-primary" type="submit">Update</button>
                    </div>
                </fieldset>
            </form>
        </div>
        
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-6 footer-navigation">
                        <h3><a href="#">TREAT Me</a></h3>
                        <p class="links"><a href="#">Resturants</a><strong> · </strong><a href="#">Services</a><strong> · </strong><a href="#">Order </a><strong> </strong></p>
                        <p class="company-name">TREAT Me @2020</p>
                    </div>
                    <div class="col-md-4 col-sm-6 footer-contacts">
                        <div><span class="fa fa-map-marker footer-contacts-icon"> </span>
                            <p><span class="new-line-span">Gollamari Khulna, Bangladesh</span></p>
                        </div>
                        <div><i class="fa fa-phone footer-contacts-icon"></i>
                            <p class="footer-center-info email text-left"> 123456789</p>
                        </div>
                        <div><i class="fa fa-envelope footer-contacts-icon"></i>
                            <p> <a href="#" target="_blank">support@company.com</a></p>
                        </div>
                        <div><i class="fa fa-envelope footer-contacts-icon"></i>
                            <p> <a href="#" target="_blank">AtoZ@gmail.com</a></p>
                        </div>
                        
                    </div>
                    <div class="clearfix visible-sm-block"></div>
                    <div class="col-md-4 footer-about">
                        <h4>About the company</h4>
                        <p> Lorem ipsum dolor sit amet, consectateur adispicing elit. Fusce euismod convallis velit, eu auctor lacus vehicula sit amet. </p>
                        <div class="social-links social-icons"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-linkedin"></i></a><a href="#"><i class="fa fa-github"></i></a></div>
                    </div>
                </div>
            </div>
        </footer>
    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.8.2/js/lightbox-plus-jquery.min.js"></script>
</body>

</html>